# Generated by Django 5.1.6 on 2025-02-09 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_types', models.CharField(choices=[('game_development', 'Game Development'), ('web_development', 'Web Development'), ('data_visualizaion', 'Data Visualization'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='services/images/')),
                ('description', models.TextField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
